name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup latest .NET SDKs
      # You may pin to the exact commit or the version.
      # uses: Elskom/setup-latest-dotnet@908aae4113c27b157acc40625a3495c80b29f407
      uses: Elskom/setup-latest-dotnet@v1.1.2
        with:
        # Major version of the .NET SDK to install.
        VERSION_MAJOR: # optional, default is 7
        # Minor version of the .NET SDK to install.
        VERSION_MINOR: # optional, default is 0
        # Band version of the .NET SDK to install.
        VERSION_BAND: # optional, default is 1xx
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
